### ISSUE TITLE
Using gdthumb plugin

### ISSUE THREAD

**Issue by odvdveer** [Philio/bootstrapdefault#8] opened 2015-07-19 21:27 UTC
Hi,

I am experimenting with the bootstrap-default theme and greydragon theme with the gdThumb plugin. I love the way the bootstrap-default theme can adjust the navbar on small screens but have a problem with the gdthumb plugin.

The gdthumb plugin works fine on the album page but not on the content of the album page. Is there a way to correct this behavour ?

My test homepage: http://s1018887-37971.mijnreus.nl/odvdveer.nl/piwigo/

**Comment by Philio** [comment] 2015-07-19 21:35
Can you confirm which version you're using? I'm sure gdThumb was working before!

**Comment by odvdveer** [comment] 2015-07-19 21:45
Hello,

I am using  1.0.0-rc1 (just upgraded an hour ago from the previous ( a 
rc 3 ) version

Is there a way to remove the icons for list and other view as they are 
not working with the plugin or should this also work?

Regards,
Olga



Op 19-7-2015 om 23:35 schreef Phil Bayfield:

**Comment by Philio** [comment] 2015-07-19 21:46
I have replicated it on one of my test sites, I'll see if I can fix it in the next release.

**Comment by odvdveer** [comment] 2015-07-19 21:58
Thank you :)

Op 19-7-2015 om 23:46 schreef Phil Bayfield:

**Comment by Philio** [comment] 2015-07-19 22:02
A bit strange really, I see gdThumb is based on GThumb+.
GThumb+ works, gdThumb doesn't!

**Comment by odvdveer** [comment] 2015-07-19 22:27
Tested,
and
yes with only GThumb+ the page showing the photos in the album works 
fine but not the page with the (sub) albums,  and the icons for list and 
other view disappear.
With only gdThumb it works (exept the icons stay) on the (sub) album 
pages and not on the photo page.
With both plugins activated thing almost work perfectly, Only the icons 
stay visible on the (sub)album pages and do nothing.


Op 20-7-2015 om 00:02 schreef Phil Bayfield:

**Comment by Philio** [comment] 2015-07-19 22:56
I have worked out what the problem is, in fact both plugins have the same issue but as the JS works a bit differently in GThumb+ it works regardless.

I'll keep digging, I don't think it'll be a hugely complicated thing to fix.

**Comment by Philio** [comment] 2015-07-19 23:30
Fixed in RC2

**Closed by Philio** 2015-07-19 23:30 UTC
Labels: bug

**Comment by odvdveer** [comment] 2015-07-20 19:29
Sorry to bother you again but the *btn-grid and btn-list *are still  
visible when using gdthumb. Is there a way to make them invisible as 
happens with GThumb+



Op 20-7-2015 om 01:30 schreef Phil Bayfield:

**Comment by Philio** [comment] 2015-07-20 20:36
I wasn't aware there was anything special in place to do that, but I'll have a look.

**Comment by Philio** [comment] 2015-07-20 20:43
Ok, look out for the next release, probably by the end of the week.

**Comment by odvdveer** [comment] 2015-07-20 20:53
Thank you for the fast response :)

Regards

Op 20-7-2015 om 22:43 schreef Phil Bayfield:
